# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  run-tests:
    docker:
      - image: node:20-alpine
    steps:
      - checkout
      - run: 'corepack enable'
      - run: 'yarn --immutable'
      # - run: 'yarn prisma:generate'
      - run: 'yarn test:ci'

workflows:
  test-workflow:
    jobs:
      - run-tests
